//
//  SearchModels.swift
//  MySound
//
//  Created by Игорь Ноек on 19.04.2020.
//  Copyright (c) 2020 Игорь Ноек. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
  // MARK: Use cases
  
  enum Model
  {
    
    struct Request
    {
        enum RequestType {
            case getTracks(searchTerm: String)
        }
    }
    
    
    struct Response
    {
        enum ResponseType {
            case presentTracks(searchResponse: RespondModel?)
            case presentFooterView
        }
    }
    
    
    struct ViewModel
    {
        enum ViewModelData {
            case displayTracks(searchViewModel: SearchViewModel)
            case displayFooterView
        }
        
    }
    
  }

}
//TrackModel
struct SearchViewModel {
    struct Cell: TrackCellViewModel {
        var iconUrlString: String?
        
        var trackName: String
        
        var artistName: String
        
        
        var collectionString: String
        
//        var iconUrlString: String?
//        var trackName: String
//        var collectionString: String?
//        var artistName: String
        var previewUrl: String?
    }
    
    let cells: [Cell]
}
