//
//  SearchInteractor.swift
//  MySound
//
//  Created by Игорь Ноек on 19.04.2020.
//  Copyright (c) 2020 Игорь Ноек. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
//запрос к сетевым данным или базам данных
protocol SearchBusinessLogic
{
    func makeRequest(request: Search.Model.Request.RequestType)
}



class SearchInteractor: SearchBusinessLogic
{
    
    var presenter: SearchPresentationLogic?
    var worker: SearchWorker?
    var networkService = NetworkService()
    
    func makeRequest(request: Search.Model.Request.RequestType) {
        if worker == nil {
            worker = SearchWorker()
        }
        
        switch request {
        case .getTracks(let searchTerm):
            //вызывается функция модели networkService, получающая значение из поиска
            //полученные данные идут в presenter
            networkService.fetchTracks(searchText: searchTerm) { [weak self] (searchResponse) in
                //отпраляем данные из searchBar в presenter
                self?.presenter?.presentData(response: Search.Model.Response.ResponseType.presentTracks(searchResponse: searchResponse))
            }
            
        }
        
    }
}



